#!/usr/bin/with-contenv bash

# Check if the SYS_ADMIN cap is set
if ! capsh --has-p=cap_sys_admin; then
    echo "Required capability SYS_ADMIN is missing"
    exit 1
fi

# Check if /dev/shm is large enough (2GB at least)
if ! shm-check; then
    echo "/dev/shm must be at least 2GB in size"
    exit 1
fi

if [[ -z $SIP_JIBRI_XMPP_PASSWORD || -z $JIBRI_XMPP_PASSWORD ]]; then
    echo 'FATAL ERROR: Sip-Jibri XMPP password and auth password must be set'
    exit 1
fi

OLD_SIP_JIBRI_XMPP_PASSWORD=passw0rd
if [[ "$SIP_JIBRI_XMPP_PASSWORD" == "$OLD_SIP_JIBRI_XMPP_PASSWORD" ]]; then
    echo 'FATAL ERROR: Sip-Jibri XMPP password must be changed, check the README'
    exit 1
fi

OLD_JIBRI_XMPP_PASSWORD=passw0rd
if [[ "$JIBRI_XMPP_PASSWORD" == "$OLD_JIBRI_XMPP_PASSWORD" ]]; then
    echo 'FATAL ERROR: Jibri auth password must be changed, check the README'
    exit 1
fi

# set random jibri nickname for the instance if is not set
[ -z "${SIP_JIBRI_INSTANCE_ID}" ] && export SIP_JIBRI_INSTANCE_ID="sip-jibri-$(date +%N)"

# always recreate configs
tpl /defaults/jibri.conf > /etc/jitsi/jibri/jibri.conf
tpl /defaults/logging.properties > /etc/jitsi/jibri/logging.properties
tpl /defaults/xorg-video-dummy.conf > /etc/jitsi/jibri/xorg-video-dummy.conf
tpl /defaults/pjsua.config > /etc/jitsi/jibri/pjsua.config

# make logs dir
JIBRI_LOGS_DIR=/config/logs
mkdir -p ${JIBRI_LOGS_DIR}
chown -R jibri ${JIBRI_LOGS_DIR}
